### ISSUE TITLE
QEmu fatal error on M1 Mac with Docker Desktop and minikube

### ISSUE THREAD

**Issue by tommy2d** [kubevirt/kubevirt.github.io#930]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

Trying to start https://kubevirt.io/labs/manifests/vm.yaml and open a console to it. The VirtualMachineInstance shows the following error:
```
'server error. command SyncVMI failed: "LibvirtError(Code=67, Domain=10,
      Message=''unsupported configuration: CPU mode ''host-passthrough'' for aarch64
      qemu domain on aarch64 host is not supported by hypervisor'')"'
```

**What you expected to happen**:

Console should open, showing that VMs output.

**Anything else we need to know?**:

Running on an M1 Max, on top op Docker Desktop with Docker Engine v24.0.6, using minikube v1.32.0 on Darwin 14.2 (arm64).

I enabled emulation:

```
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      useEmulation: true
```

What am I missing? I understand I need emulation on a ARM Mac because of platform limitations.
